### ISSUE TITLE
XGBoostError opening G4Boost_regressor.json failed: no such file or directory

### ISSUE THREAD

**Issue by rmons01** [hbusra/G4Boost#1]
Trying to test the G4boost.py script with defaults and a single file test.fa with 'GGGAGGGTGGGAGGG' as its only contents and received the following:

```
Processing GGGAGGGTGGGAGGG
Starting stability prediction!

Traceback (most recent call last):
  File "/home/shared/G4Boost/G4Boost.py", line 252, in <module>
    regressor.load_model(args.regressor)
  File "/home/robert/tutorial-env/lib64/python3.6/site-packages/xgboost/sklearn.py", line 599, in load_model
    self.get_booster().load_model(fname)
  File "/home/robert/tutorial-env/lib64/python3.6/site-packages/xgboost/core.py", line 2170, in load_model
    self.handle, c_str(fname)))
  File "/home/robert/tutorial-env/lib64/python3.6/site-packages/xgboost/core.py", line 218, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [16:09:15] ../src/common/io.cc:102: Opening G4Boost_regressor.json failed: No such file or directory
Stack trace:
  [bt] (0) /home/robert/tutorial-env/lib64/python3.6/site-packages/xgboost/lib/libxgboost.so(+0xc94ed) [0x7fcba139a4ed]
  [bt] (1) /home/robert/tutorial-env/lib64/python3.6/site-packages/xgboost/lib/libxgboost.so(+0xc9ada) [0x7fcba139aada]
  [bt] (2) /home/robert/tutorial-env/lib64/python3.6/site-packages/xgboost/lib/libxgboost.so(XGBoosterLoadModel+0x379) [0x7fcba136f9b9]
  [bt] (3) /lib64/libffi.so.6(ffi_call_unix64+0x4c) [0x7fcbeb921dcc]
  [bt] (4) /lib64/libffi.so.6(ffi_call+0x1f5) [0x7fcbeb9216f5]
  [bt] (5) /usr/lib64/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2a0) [0x7fcbebb34680]
  [bt] (6) /usr/lib64/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x97c6) [0x7fcbebb2d7c6]
  [bt] (7) /lib64/libpython3.6m.so.1.0(_PyObject_FastCallDict+0x90) [0x7fcc322eed20]
  [bt] (8) /lib64/libpython3.6m.so.1.0(+0x1522fc) [0x7fcc323982fc]
```

It seems to be looking for the file 'G4Boost_regressor.json' even though that should be an optional argument, correct?

**Comment by hbusra** [comment]
Hey, thanks for contacting me for this. There is an option to use a
different regressor or classifier but at default G4Boost requires the two
prebuilt models, namely G4Boost_regressor and G4Boost_classifier. The
python script and the two json files should be in the same folder. If they
are in the same folder, you don’t need to specify the prediction models as
a parameter.

Please let me know if you have any other questions,
Best,
Busra

**Comment by rmons01** [comment]
Oh I see. Thank you it works great!
