### ISSUE TITLE
G4Boost.py only generates gff file and does not generate csv file

### ISSUE THREAD

**Issue by subriotech** [hbusra/G4Boost#4]
HI,

I am trying to run G4boost on a multifasta file, and it generates only the gff file and not the csv file.

**Comment by subriotech** [comment]
This is the error I am getting when I try to run the test sequence. :

Processing test_seq_1
Starting stability prediction!
[12:29:35] WARNING: /croot/xgboost-split_1675457761144/work/src/learner.cc:888: Found JSON model saved before XGBoost 1.6, please save the model using current version again. The support for old JSON model will be discontinued in XGBoost 2.3.
[12:29:35] WARNING: /croot/xgboost-split_1675457761144/work/src/learner.cc:888: Found JSON model saved before XGBoost 1.6, please save the model using current version again. The support for old JSON model will be discontinued in XGBoost 2.3.
Traceback (most recent call last):
  File "/oak/stanford/scg/lab_tessier3/Subbu/G4Boost/new_3UTR/test/G4Boost-main/G4Boost.py", line 262, in <module>
    g4_pred=classifier.predict(X_test)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/subbu09/miniconda3/lib/python3.11/site-packages/xgboost/sklearn.py", line 1525, in predict
    class_probs = super().predict(
                  ^^^^^^^^^^^^^^^^
  File "/home/subbu09/miniconda3/lib/python3.11/site-packages/xgboost/sklearn.py", line 1114, in predict
    predts = self.get_booster().inplace_predict(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/subbu09/miniconda3/lib/python3.11/site-packages/xgboost/core.py", line 2285, in inplace_predict
    self._validate_features(fns)
  File "/home/subbu09/miniconda3/lib/python3.11/site-packages/xgboost/core.py", line 2779, in _validate_features
    raise ValueError(msg.format(self.feature_names, feature_names))
ValueError: feature_names mismatch: ['length', 'len', 'maxgstem', 'maxgbase', 'maxlbase', 'minlbase', 'G', 'C', 'GG', 'CC'] ['seq_length', 'length', 'loops', 'G-quartet', 'maxlbase', 'minlbase', 'G', 'C', 'GG', 'CC']
expected len, maxgbase, maxgstem in input data
training data did not have the following fields: loops, seq_length, G-quartet

**Comment by subriotech** [comment]
ValueError: feature_names mismatch: ['length', 'len', 'maxgstem', 'maxgbase', 'maxlbase', 'minlbase', 'G', 'C', 'GG', 'CC'] ['seq_length', 'length', 'loops', 'G-quartet', 'maxlbase', 'minlbas
e', 'G', 'C', 'GG', 'CC']
expected len, maxgstem, maxgbase in input data

This is the error that I am getting

**Comment by balwierz** [comment]
I am getting the same error, on a single sequence fasta file.
This happens during stability predictions.

**Comment by hbusra** [comment]
I couldn't reproduce this error. I installed G4Boost from scratch and performed a test run. It's working.
Here are the steps I took to install and setup:
1- Download G4Boost directory from GitHub
2- Unzip the downloaded G4Boost
3- create a conda environment
conda create -y --name G4Boost_env python=3.9
conda activate G4Boost_env
pip3 install pandas==1.4.3
pip3 install scikit-learn
pip3 install xgboost==1.4.2
4- test run
python3 G4Boost.py -f test.fa 

This steps should produce a gff and a csv file. Could you please provide me the sample sequence?

Here are the things to make sure:
1- Do you have prediction models (.json files) downloaded at the same directory?
2- Do you have the versions of the modules listed above installed?

**Comment by balwierz** [comment]
Thanks, that specific package versions did work!
My original versions were:
Python             3.10
pandas             2.1.1
scikit-learn       1.4.0
xgboost            2.0.3
